const mongoose = require("mongoose");

// Schema for documentation sections
const sectionSchema = new mongoose.Schema(
  {
    id: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    content: {
      type: String,
      required: true,
    },
    order: {
      type: Number,
      required: true,
    },
    type: {
      type: String,
      enum: [
        "overview",
        "getting-started",
        "phase-guide",
        "resources",
        "tips",
        "faq",
      ],
      default: "overview",
    },
  },
  { _id: false }
);

// Schema for documentation resources
const docResourceSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
    },
    description: {
      type: String,
    },
    url: {
      type: String,
      match: [/^https?:\/\/.+/, "Please provide a valid URL"],
    },
    type: {
      type: String,
      enum: [
        "video",
        "article",
        "course",
        "book",
        "documentation",
        "tutorial",
        "tool",
      ],
      required: true,
    },
    category: {
      type: String,
      enum: ["beginner", "intermediate", "advanced", "reference", "practice"],
    },
    free: {
      type: Boolean,
      default: true,
    },
    rating: {
      type: Number,
      min: 1,
      max: 5,
    },
  },
  { _id: false }
);

// Main documentation schema
const documentationSchema = new mongoose.Schema({
  roadmapId: {
    type: String,
    required: true,
    unique: true,
  },
  roadmapObjectId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Roadmap",
    required: true,
  },

  // Documentation content
  title: {
    type: String,
    required: true,
    trim: true,
  },

  // Raw markdown content (as generated by AI)
  markdownContent: {
    type: String,
    required: true,
  },

  // Parsed HTML content (for faster rendering)
  htmlContent: {
    type: String,
  },

  // Structured sections for better organization
  sections: [sectionSchema],

  // Additional resources curated for this roadmap
  additionalResources: [docResourceSchema],

  // Table of contents (auto-generated from sections)
  tableOfContents: [
    {
      title: String,
      anchor: String,
      level: Number,
      order: Number,
    },
  ],

  // SEO and metadata
  seo: {
    title: {
      type: String,
      maxlength: [60, "SEO title cannot be more than 60 characters"],
    },
    description: {
      type: String,
      maxlength: [160, "SEO description cannot be more than 160 characters"],
    },
    keywords: [
      {
        type: String,
      },
    ],
    slug: {
      type: String,
      unique: true,
      match: [
        /^[a-z0-9-]+$/,
        "Slug can only contain lowercase letters, numbers, and hyphens",
      ],
    },
  },

  // Content metrics
  metrics: {
    wordCount: {
      type: Number,
      default: 0,
    },
    readingTimeMinutes: {
      type: Number,
      default: 0,
    },
    lastReadAt: {
      type: Date,
    },
    viewCount: {
      type: Number,
      default: 0,
    },
  },

  // Version control
  version: {
    type: String,
    default: "1.0",
  },
  revisionHistory: [
    {
      version: String,
      changes: String,
      updatedBy: {
        type: String,
        enum: ["ai", "admin", "community"],
        default: "ai",
      },
      updatedAt: {
        type: Date,
        default: Date.now,
      },
    },
  ],

  // Publishing status
  status: {
    type: String,
    enum: ["draft", "published", "archived"],
    default: "published",
  },

  // AI generation metadata
  aiGeneration: {
    model: {
      type: String,
      required: true,
    },
    prompt: {
      type: String,
    },
    generatedAt: {
      type: Date,
      default: Date.now,
    },
    tokens: {
      input: Number,
      output: Number,
      total: Number,
    },
  },

  // User feedback
  feedback: {
    helpful: {
      type: Number,
      default: 0,
    },
    notHelpful: {
      type: Number,
      default: 0,
    },
    comments: [
      {
        userId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
        },
        comment: {
          type: String,
          maxlength: [500, "Comment cannot be more than 500 characters"],
        },
        createdAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],
  },

  // Timestamps
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

// Indexes for performance
documentationSchema.index({ roadmapId: 1 });
documentationSchema.index({ "seo.slug": 1 });
documentationSchema.index({ status: 1, createdAt: -1 });
documentationSchema.index({ "metrics.viewCount": -1 });

// Pre-save middleware
documentationSchema.pre("save", function (next) {
  this.updatedAt = Date.now();

  // Calculate word count and reading time
  if (this.markdownContent) {
    const words = this.markdownContent.split(/\s+/).length;
    this.metrics.wordCount = words;
    this.metrics.readingTimeMinutes = Math.ceil(words / 200); // Average reading speed
  }

  // Generate slug if not provided
  if (!this.seo.slug && this.title) {
    this.seo.slug = this.title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .trim("-");
  }

  next();
});

// Method to increment view count
documentationSchema.methods.incrementViewCount = function () {
  this.metrics.viewCount += 1;
  this.metrics.lastReadAt = new Date();
  return this.save();
};

// Method to add feedback
documentationSchema.methods.addFeedback = function (
  isHelpful,
  comment = "",
  userId = null
) {
  if (isHelpful) {
    this.feedback.helpful += 1;
  } else {
    this.feedback.notHelpful += 1;
  }

  if (comment && userId) {
    this.feedback.comments.push({
      userId,
      comment,
      createdAt: new Date(),
    });
  }

  return this.save();
};

// Method to update content and create revision
documentationSchema.methods.updateContent = function (
  newContent,
  changes = "",
  updatedBy = "ai"
) {
  // Create revision history entry
  this.revisionHistory.push({
    version: this.version,
    changes,
    updatedBy,
    updatedAt: new Date(),
  });

  // Update version
  const versionParts = this.version.split(".");
  const minor = parseInt(versionParts[1]) + 1;
  this.version = `${versionParts[0]}.${minor}`;

  // Update content
  this.markdownContent = newContent;

  return this.save();
};

// Static method to get popular documentation
documentationSchema.statics.getPopular = function (limit = 10) {
  return this.find({ status: "published" })
    .sort({ "metrics.viewCount": -1, "feedback.helpful": -1 })
    .limit(limit)
    .populate("roadmapObjectId", "title field level");
};

// Static method to search documentation
documentationSchema.statics.search = function (query, limit = 20) {
  return this.find({
    status: "published",
    $or: [
      { title: { $regex: query, $options: "i" } },
      { markdownContent: { $regex: query, $options: "i" } },
      { "seo.keywords": { $regex: query, $options: "i" } },
    ],
  })
    .limit(limit)
    .populate("roadmapObjectId", "title field level")
    .sort({ "metrics.viewCount": -1 });
};

// Virtual for helpfulness ratio
documentationSchema.virtual("helpfulnessRatio").get(function () {
  const total = this.feedback.helpful + this.feedback.notHelpful;
  if (total === 0) return 0;
  return Math.round((this.feedback.helpful / total) * 100);
});

// Transform JSON output
documentationSchema.methods.toJSON = function () {
  const obj = this.toObject();
  obj.helpfulnessRatio = this.helpfulnessRatio;
  obj.url = `/docs/${this.seo.slug}`;
  return obj;
};

module.exports = mongoose.model("Documentation", documentationSchema);
